// src/app/pages/about/about.component.ts
import { Component } from '@angular/core';
import { Title } from '@angular/platform-browser';

const birthday = 845971200000;
const oneDay = 8.64e+7;
const seventhYears = 5.361e+11;

@Component({
  selector: 'solomon-about',
  templateUrl: './about.component.html',
})
export class AboutComponent {

  days = Math.floor((Date.now() - birthday - seventhYears) / oneDay);

  constructor (private titleService: Title) {
    this.titleService.setTitle('about | solomon');
  }

}

<div class="about-theme">
  <solomon-header></solomon-header>
  <div class="container">
    <h1 class="primary-header">About</h1>
    <article>
      <section>
        <h2>poi</h2>
        <div class="section-content">
          <p>林培奇（Alex Lin），17 岁零 {{days}} 天。</p>
          <p>理想是建造沃登克里弗塔（Wardenclyffe Tower）。</p>
          <p>如果你想快速了解我可以查看：<a href="https://poi.cat/zh-Hans">poi-cat</a>。</p>
        </div>
      </section>
      <section>
        <h2>gpg</h2>
        <div class="section-content">
          <p>我的 PGP 指纹：<code>EC56 5FE9 8A6F 316A B69F 6979 8EE0 5E84 4452 6ED5</code>。</p>
          <p>你可以从 Keybase 或是我的博客上导入我的公钥。当然，建议你都运行一次，以防止被更改：</p>
          <pre><code><span class="hljs-comment"># import my gpg key from my blog</span>
<span class="hljs-meta">$</span> curl https://blog.poi.cat/poi.gpg | gpg --import

<span class="hljs-comment"># from keybase, too</span>
<span class="hljs-meta">$</span> curl https://keybase.io/poiscript/pgp_keys.asc | gpg --import</code></pre>
          <p>如无异样，gpg 应该会显示：<b>"Alex Lin (poi) &lt;poiscript@gmail.com&gt;" not changed</b>； </p>
          <p>如有异样，请先运行
            <code>gpg --delete-keys POI_KEY_ID</code>
            清除已导入的可疑的 key，然后再联系我解决。 >_<
          </p>
        </div>
      </section>
      <section>
        <h2>solomon</h2>
        <div class="section-content">
          <p>solomon 是我的博客的名字，同时也是该博客框架的名字。</p>
          <p>
            目前 solomon 基于 <a href="https://angular.io">Angular</a> 和 <a href="https://material.angular.io/">
            Angular Material</a>， 使用 <a href="https://cli.angular.io/">Angular CLI</a> 构建。
          </p>
          <p>
            博客的框架以 <a href="https://github.com/PoiScript/solomon/blob/master/LICENSE">MIT协议</a> 在 GitHub 上开源，文章在
            <a href="https://github.com/PoiScript/solomon-post/blob/master/LICENSE">知识共享 署名-相同方式共享 4.0协议</a>
            下提供。
          </p>
        </div>
      </section>
    </article>
  </div>
</div>

// src/pages/About.jsx
import React from 'react'
import { Helmet } from 'react-helmet'

import Main from '../components/Main'
import Forever17 from '../components/Forever17'

const frameworkLicenseUrl = 'https://github.com/PoiScript/solomon/blob/master/LICENSE'
const contentLicenseUrl = 'https://github.com/PoiScript/solomon-post/blob/master/LICENSE'

/**
 * @constructor
 */
const About = () => (
  <Main title='About'>
    <Helmet title='About - Solomon' />
    <article>
      <h2 id='about-me'>我</h2>
      <p>林培奇 (Alex Lin), <Forever17 birthday='1996-10-22' />.</p>
      <p>PGP 指纹: <code>5512 A261 68C3 F1C0 2E72 8E6F 1751 38ED 8C51 AA0D</code>.</p>
      <p>从 Keybase 导入我的公钥:</p>
      <pre>
        <code>$ gpg --fetch-keys https://keybase.io/PoiScript/key.asc</code>
      </pre>
      <p>其他信息可以查阅: <a href='https://poi.cat/zh-Hans'>poi-cat</a>.</p>
      <h2 id='about-solomon'>Solomon</h2>
      <p>Solomon 是我的博客的名字, 同时也是该博客框架的名字.</p>
      <p>博客的框架以 <a href={frameworkLicenseUrl}>MIT协议</a> 开源.</p>
      <p>文章在 <a href={contentLicenseUrl}>知识共享 署名-相同方式共享 4.0协议</a> 下提供.</p>
    </article>
  </Main>
)

/**
 * about component
 */
export default About
