// angular/app/shared/post-list/post-list.component.ts
import { Component, Input } from '@angular/core';

import { Post } from 'app/app.types';

@Component({
  selector: 'solomon-post-list',
  templateUrl: './post-list.component.html',
  styleUrls: ['./post-list.component.scss']
})
export class PostListComponent {
  @Input() posts: Post[];
}

<div *ngIf="posts.length; then has_post else no_post"></div>

<ng-template #has_post>
  <div class="content">
    <p>{{posts.length}} posts</p>
    <div *ngFor="let post of posts">
      <a class="title" [routerLink]="['/post', post.slug]">
        {{post.title}}
      </a>
      <p>
        <span>{{post.date | date:'mediumDate'}}</span>
        <a class="title" *ngFor="let tag of post.tags" [routerLink]="['/tag', tag]">
          #{{tag}}
        </a>
      </p>
    </div>
  </div>
</ng-template>

<ng-template #no_post>
  <i>No Posts :(</i>
</ng-template>

// src/components/PostList.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { Link } from 'react-router-dom'

import './PostList.css'

/**
 * @constructor
 */
const PostList = ({ posts }) => (
  <div>
    {posts.length
      ? (
        <div className='post-list-content'>
          <p>{posts.length} posts</p>
          {posts.map((post, i) => (
            <div key={i}>
              <Link className='post-list-title' to={`/post/${post.slug}/`}>{post.title}</Link>
              <p>
                <span>{(new Date(post.date)).toDateString()}</span>
                {post.tags.map((tag, i) => (
                  <Link key={i} className='post-list-tag' to={`/tag/${tag}/`}> #{tag} </Link>
                ))}
              </p>
            </div>
          ))}
        </div>
      )
      : <i>No Posts :(</i>
    }
  </div>
)

PostList.PropTypes = {
  posts: PropTypes.arrayOf(PropTypes.shape({
    slug: PropTypes.string.isRequired,
    date: PropTypes.string.isRequired,
    tags: PropTypes.arrayOf(PropTypes.string).isRequired,
    title: PropTypes.string.isRequired
  })).isRequired
}

/**
 * postlist component
 */
export default PostList
