// web/src/app/shared/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'solomon-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {}

<footer class="solomon-footer">
  <div class="links">
    <a href="https://blog.poi.cat/atom.xml">RSS</a>
    <span class="separator">/</span>
    <a href="https://github.com/PoiScript/solomon">GitHub</a>
  </div>
  <span class="spacer"></span>
  <span class="license">Content licensed under CC-BY-SA-4.0.</span>
</footer>

// react/src/components/Footer.jsx
import React from 'react'
import { Toolbar, ToolbarGroup } from 'material-ui/Toolbar'
import FlatButton from 'material-ui/FlatButton'

const Footer = () => (
  <footer>
    <Toolbar>
      <ToolbarGroup style={{
        marginLeft: 'auto',
        marginRight: 'auto'
      }}>
        <FlatButton
          style={{marginLeft: 0, marginRight: 0}}
          href='https://poi.works/atom.xml'
          label='rss' />
        <FlatButton
          style={{marginLeft: 0, marginRight: 0}}
          href='https://github.com/PoiScript/Solomon'
          label='github' />
        <FlatButton
          style={{marginLeft: 0, marginRight: 0}}
          href='https://amp.poi.works'
          label='amp' />
      </ToolbarGroup>
    </Toolbar>
    <Toolbar>
      <ToolbarGroup style={{
        marginLeft: 'auto',
        marginRight: 'auto'
      }}>
        All Content Licensed Under CC-BY-SA-4.0
      </ToolbarGroup>
    </Toolbar>
  </footer>
)

export default Footer
